#######################################
# Rosechat General Configuration File #
#######################################

# Should the plugin check for a message full of capital letters? #
caps-check: true

# The maximum amount of capital letters that are allowed in a message. #
# Allows players to use words like 'LOL'. #
max-amount-of-caps: 5

# Should the plugin lowercase capital messages? #
# If false, the message will not be sent. Disable caps-check to send messages full of capital letters. #
lowercase-caps: true

# Should the plugin check for multiple of the same message? #
spam-check: true

# What should the plugin do when URLs are sent in chat? #
# Options: LIGHT_CENSOR - Removes the periods in the message, #
# BLOCK - Stops the message from being sent, #
# NOTHING - Players are allowed to send URLs in chat. #
url-check: LIGHT_CENSOR

# If the message contains these words, the words will be replaced. #
# Format: contains:replace with #
# Message filtering will never be perfect, 'assassin' will not be censored, but neither will 'stupidass'.
replaced-messages:
  - fuck:f***
  - bitch:dog
  - ass:butt

# If the message contains these words, the message will not be sent. #
blocked-messages:
  - faggot

# The sound sent when a player receives a message. #
# Use https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html for sounds. #
# Can be 'none'. #
message-sound: BLOCK_NOTE_BLOCK_PLING

# The sound sent when a player receives a a tag. #
# Can be 'none'. #
tag-sound: BLOCK_NOTE_BLOCK_PLING

# How a tag is defined. #
tag-prefix: "@"

# Allows tagging an offline player, only the chat message will change. #
allow-offline-tags: true

# Allows players to use PlaceholderAPI placeholders in the chat. #
allow-placeholders-in-chat: true

# All the placeholders that players are not allowed to use in chat. #
blacklisted-chat-placeholders:
  - "Server"
  - "%player_ip%"

# The radius of the radius chat channel. #
# Can be set to 0 for a one-person channel. #
chat-radius: 200

formats:

  # The format of the chat. #
  # Define placeholders under custom-placeholders. #
  # Only placeholders can be used, no other characters. #
  # You can use {message} to define where the message displays. #
  chat-format: "{prefix}{player}{extra}{message}"

  # The format of a /message send to another player. #
  message-sent-format: "{left-bracket}{player}{arrow}{receiver}{right-bracket}{message}"

  # The format of a /message sent from another player. #
  message-received-format: "{left-bracket}{player}{arrow}{receiver}{right-bracket}{message}"

  # The format of the staff chat. #
  staff-chat-format: "{staff-prefix}{player}{extra}{message}"

  # The format of a tag. #
  tagging-format: "{tag}"

  # The format of a spied message. #
  social-spy-format: "{spy-prefix}{spy-players}{message}"

  # The format of the radius chat, when a player is far away from the sender. #
  radius-format-far: "{player}{extra}{far-color}{message}"

  # The format of the radius chat, when a player is a medium distance away from the sender. #
  radius-format-medium: "{player}{extra}{medium-color}{message}"

  # The format of the radius chat, when a player is near the sender. #
  radius-format-near: "{player}{extra}{near-color}{message}"

  # The format of a per-world message. #
  per-world-format: "{world}{player}{extra}{message}"

  # The format of a group message. #
  group-format: "{group}{player}{extra}{message}"

  # The format of a spied group message. #
  group-spy-format: "{spy-prefix}{group}{player}{extra}{message}"

  # The format of a spied world message. #
  world-spy-format: "{spy-prefix}{world}{player}{extra}{message}"

# Custom placeholders for the different formats. #
# Allows text, hover events, click events, and placeholders from PlaceholderAPI. #
custom-placeholders:

  # This defines the {prefix} placeholder. #
  prefix:
    # Text is mandatory. A placeholder will not work without it. #
    text:
      # If the player is not in any groups specified, it will use the default. #
      # If no groups are specified, it will use the default. #
      default: "%luckperms_prefix%"
      admin: "&8[&4&lAdmin&8] "
    # This tells the plugin that the placeholder is using a hover event. #
    # Hover events show text and can have multiple lines. #
    hover:
      default:
        - "&7Username: &f%player_name%"
        - "&7Balance: &a$%vault_eco_balance_formatted%"
      admin:
        - "&7Username: &f%player_name%"
        - "&7Balance: &a$%vault_eco_balance_formatted%"
        - "&cClick to Message"
    # This tells the plugin that the placeholder is using a click event. #
    # An 'action' is what to do when the message is clicked. #
    # The 'extra' is what will be executed. #
    # Possible Actions: RUN_COMMAND, SUGGEST_COMMAND, OPEN_FILE, OPEN_URL #
    click:
      default:
        action: RUN_COMMAND
        value: "/msg %player_name% <3"
      admin:
        action: SUGGEST_COMMAND
        value: "/msg %player_name% Help, "

  player:
    text:
      default: "%essentials_nickname%"
    hover:
      default:
      - "&eClick to Message"
    click:
      default:
        action: SUGGEST_COMMAND
        value: "/msg %player_name% "

  # It is recommended that message colors are specified in the extra placeholder. #
  # This is so things like radius chat colors are included before the message. #
  extra:
    text:
      default: "&8: "
      admin: " &8>> "

  left-bracket:
    text:
      default: "&c["

  right-bracket:
    text:
      default: "&c]"

  # The %other_player% placeholder must be used to specify that it is not the sender. #
  receiver:
    text:
      default: "%other_player_essentials_nickname%"
    hover:
      default:
        - "&eClick to Message"
    click:
      default:
        action: SUGGEST_COMMAND
        value: "/msg %other_player_player_name% "

  arrow:
    text:
      default: " &c-> "

  staff-prefix:
    text:
      default: "&8[&cStaffChat&8] "
    hover:
      default:
        - "A chat channel for only staff members."

  tag:
    text:
      default: "&e@%tag%"

  spy-prefix:
    text:
      default: "&e[SocialSpy&e]"

  spy-players:
    text:
      default: "&e[%player_name% &e-> %other_player_player_name%&e]"

  far-color:
    text:
      default: "&8"

  medium-color:
    text:
      default: "&7"

  near-color:
    text:
      default: "&f"

  group:
    text:
      default: "%group_name%"