#  _____                 _____ _           _
# |  __ \               / ____| |         | |
# | |__) |___  ___  ___| |    | |__   __ _| |_
# |  _  // _ \/ __|/ _ \ |    | '_ \ / _` | __|
# | | \ \ (_) \__ \  __/ |____| | | | (_| | |_
# |_|  \_\___/|___/\___|\_____|_| |_|\__,_|\__|
#

# Moderation Settings
moderation-settings:

  # Should the plugin check for a message full of capital letters?
  # Default: true
  caps-checking-enabled: true

  # The maximum amount of capital letters that are allowed in one message.
  # Using this allows players to use acronyms and words like 'LOL'.
  # Default: 5
  maximum-caps-allowed: 5

  # Should the plugin lowercase messages found to be full of capital letters?
  # If false, the message will not be sent. Set caps-checking-enabled to false to allow message of full capital letters.
  # Default: true
  lowercase-capitals-enabled: true

  # Should the plugin send a warning message (defined in language.yml) when a player sends a message full of capital letters?
  # Default: true
  warn-on-caps-sent: true

  # Should the plugin check for multiple of the same message?
  # Default: true
  spam-checking-enabled: true

  # How many similar messages count as spam?
  # Default: 5
  spam-message-count: 5

  # How similar are the message that count as spam?
  # Default: 0.75
  spam-filter-sensitivity: 0.75

  # Should the plugin send a warning message (defined in language.yml) when a player sends a spam message?
  # Default: true
  warn-on-spam-sent: true

  # Should the plugin check for URLs and IP addresses sent in chat? #
  # Default: true
  url-checking-enabled: true

  # What should the plugin do when URLs and IP addresses are sent in chat?
  # If true, messages will be censored - removing periods.
  # If false, the message will not be sent at all.
  # Default: true
  url-censoring-enabled: true

  # Should the plugin send a warning message (defined in language.yml) when a player sends a message with a URL or IP address in it?
  # Default: true
  warn-on-url-sent: true

  # Should the plugin check for swear words?
  # Default: true
  swear-checking-enabled: true

  # How sensitive is the swear filter?
  # Sensitivity is inverted rn smfh
  # For example, a high sensitivity will block "bitch" and "bítch"
  # Default: 0.75
  swear-filter-sensitivity: 0.8

  # If a player sends a message that contains one of these words, then the message will not be sent.
  blocked-swears:
    - faggot

  # Should the plugin send a warning message (defined in language.yml) when a player sends a message with a blocked swear in it?
  # Default: true
  warn-on-blocked-swear-sent: true

  # If a player sends a message that contains one of these words, the word will be replaced.
  # Format: 'contains:replaced'.
  swear-replacements:
    - fuck:f***
    - bitch:dog
    - ass:butt

  # Should the plugin send a warning message (defined in language.yml) when a player sends a message with a replaced swear in it?
  # Default: true
  warn-on-replaced-swear-sent: true

# Emote Settings
# Emotes replace words that are sent in chat, e.g. a player types "i <3 u", it becomes "i ❤ u"
emotes:
  # The ID of the emote.
  heart:
    # The text that gets replaced.
    text: "<3"
    # The replacement.
    replacement: "❤"
  kawaii:
    text: ":kawaii:"
    replacement: "(づ｡◕‿‿◕｡)づ"

show-emote-name-on-hover: true
show-emote-format: "&b&o%text%"

# Tags
# Tags can be used to tag specific players, or add extra detail to a message in chat.
# Tags use custom placeholders (see the custom-placeholders section) to allow hoverable and clickable tags.
tags:

  # The ID of the tag. #
  # This tag allows players to use @<player>, e.g. "Hey @Lilac!".
  player:
    # This is what the player will use to start a tag.
    prefix: "@"
    # This allows the tag to target online players.
    tag-online-players: true
    # The sound that will be sent to the player who receives the tag.
    # Valid sounds can be found at: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
    # Can also be 'none' for no sound.
    sound: BLOCK_NOTE_BLOCK_PLING
    # The format for this tag (see the formats section for more info).
    format: "{player-tag}"

  # This tag allows players to use hashtags in-game.
  # E.g. "#rosewood".
  hashtag:
    prefix: "#"
    format: "{hashtag}"

  # This tag allows players to type money in-game, and make it formatted and hoverable.
  # E.g. "$500".
  money:
    prefix: "$"
    format: "{money-tag}"

  spoiler:
    prefix: "[["
    suffix: "]]"
    format: "{spoiler-tag}"

  # This tag is used as a way to show conditional placeholders.
  condition:
    prefix: "?["
    suffix: "]"
    tag-online-players: false
    format: "{conditional-example}"

# General miscellaneous settings.
chat-settings:

  # The sound that will be sent to a player when they receive a message.
  # Valid sounds can be found at: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
  # Can also be 'none' for no sound.
  # Default: BLOCK_NOTE_BLOCK_PLING
  message-sound: BLOCK_NOTE_BLOCK_PLING

  # Should players be able to use PlaceholderAPI placeholders in chat?
  # Default: true
  chat-placeholders-enabled: true

  # These are PlaceholderAPI placeholders that are not allowed to be used in chat.
  # Placeholders that do not use % symbols will blacklist all placeholders from that expansion.
  # E.g. "Server" will block all Server placeholders, such as %server_name% and %server_version%.
  blacklisted-chat-placeholders:
    - "Server"
    - "%player_ip%"

  # These are replacements, similar to swears or emotes that can be used in chat.
  # These replacements can be used with custom placeholders (see below).
  # These can also support regular expressions.
  # The %message% placeholder allows you to replace the message with its self, this can allow changing colour for specific words.
  chat-replacements:
    - "rosechat:<g:#8A2387:#E94057:#F27121>RoseChat"
    - "&g:#C0FFEE"
    - "&h:#C8A2C8"
    - "replace me:{replacement}"
    - "[regex]:&9%message%"

# Chat Channels
chat-channels:

  # The ID of the channel, the player will use this to join the channel, e.g. /c global
  global:
    # This sets this channel as the default channel that players will be placed into once they first join the server.
    default: true
    # This is the format of this channel.
    format: "{prefix}{player}{extra}{message}"
    # Overriden Values
    # These settings can be used to override the default values in specific chat channels.
    #chat-placeholders-enabled: false
    #disabled-tags:
    #  - money
    #disabled-emotes:
    #  - kawaii
    #caps-checking-enabled: false
    #url-checking-enabled: false
    #spam-checking-enabled: false
    #swear-checking-enabled: false

  # /c staff
  staff:
    format: "{staff-prefix}{player}{extra}{message}"
    caps-checking-enabled: false
    url-checking-enabled: false
    spam-checking-enabled: false
    swear-checking-enabled: false

  # /c local
  local:
    # If no format is given, it will use the same format as the default channel.
    # The radius for players for messages in this channel to be sent to.
    radius: 200

  skyblock:
    # World channels allow messages to be sent in this channel only if they in the world. this makes no sense im crying
    world: skyblock
    # When auto-join true is combined with a world channel, as soon as the player joins this world they will be added to the channel.
    auto-join: true

    # Bungee Stuff for cross-server channels?

# Formats
chat-formats:
  # The format of a /message send to another player. #
  message-sent: "{left-bracket}{you}{arrow}{receiver}{right-bracket}{message}"

  # The format of a /message sent from another player. #
  message-received: "{left-bracket}{player}{arrow}{you}{right-bracket}{message}"

  # The format of a spied message. #
  social-spy: "{spy-prefix}{spy-players}{message}"

  # The format of a group message. #
  group: "{group}{player}{extra}{message}"

  # The format of a spied group message. #
  group-spy: "{spy-prefix}{group}{player}{extra}{message}"

  # The format of a spied world message. #
  world-spy: "{spy-prefix}{world}{player}{extra}{message}"

# Placeholders
# These allow text, hover events, click events and placeholders from PlaceholderAPI.
# The {message} placeholder is reserved for sent messages. You can set the colour of a message using the placeholder before {message},
# e.g. the {extra} placeholder ends with &7, this changes the message colour to grey.
custom-placeholders:

  # The ID of the placeholder. This defines the {prefix} placeholder.
  prefix:
    # This is the text that will be shown.
    text:
      # These are a list of groups and the prefixes that will be used for them.
      # If the player is not in any of the groups, it will use the default.
      # If Vault is not installed, it will use the default.
      # If the player is in more than one group it will use the primary group.
      default: "&7"
      admin: "&8[&cAdmin&8] "
    # This tells the plugin that this placeholder is using a hover event.
    # Hover events show text and can have multiple lines.
    hover:
      default:
        - "&cThis player administrates the server!"

  player:
    text:
      default: "%player_displayname%"
    hover:
      # The %player_name% placeholder is included in RoseChat, but most placeholders will need PlaceholderAPI.
      # For example, the %vault_eco_balance_formatted% placeholder requires the Vault expansion for PlaceholderAPI.
      default:
        - "&7Username: &f%player_name%"
        - "&7Click to Message"
        - "&7Balance: &a$%vault_eco_balance_formatted%"
    # This tells the plugin that the placeholder is using a click event.
    # An 'action' is what to do when the message is clicked.
    # The 'extra' is what will be executed.
    # Valid Actions: RUN_COMMAND, SUGGEST_COMMAND, OPEN_FILE, OPEN_URL
    click:
      default:
        action: SUGGEST_COMMAND
        value: "/msg %player_name% "

  extra:
    text:
      default: "&7: &7"
      admin: " &e» &f"

  staff-prefix:
    text:
      default: "&8[&cStaffChat&8]"
    hover:
      default:
        - "&7A chat channel that only staff members can see."

  left-bracket:
    text:
      default: "&8["

  right-bracket:
    text:
      default: "&8] "

  arrow:
    text:
      default: " &6->&r "
    # RoseChat allows "other_" to be placed in front of PlaceholderAPI player placeholders to target the second player.
    # This can be used in a /message, or a tag.
    hover:
      default:
        - "&6From: &f%player_name%"
        - "&eTo: &f%other_player_name%"

  receiver:
    text:
      default: "%other_player_displayname%"
    hover:
      default:
        - "&7Balance: &a$%vault_eco_balance_formatted%"

  you:
    text:
      default: "&eYou"

  # The "%tag%" placeholder represents the message the player types, e.g.
  # If a player typed "@Lilac", '%tag%' would be replaced with 'Lilac'.
  player-tag:
    text:
      default: "&e@%tag%"
    hover:
      default:
        condition-type: PLACEHOLDER
        condition: "%player_online%"
        true:
          - "&aOnline"
        false:
          - "&cOffline"

  hashtag:
    text:
      default: "&9#%tag%"

  money-tag:
    text:
      default: "&a$%tag%"
    hover:
      default:
        - "&7Click to pay &c%player% &a$%tag%"
    click:
      default:
        action: SUGGEST_COMMAND
        value: "/pay %player% %tag%"

  spoiler-tag:
    text:
      default: "&0⬛⬛⬛⬛⬛"
    hover:
      default: "%tag%"

  conditional-example:
    text:
      default: "&c⬛⬛⬛⬛⬛"
    hover:
      condition-type: PERMISSION
      condition: "rosechat.staffhover"
      true:
        - "%tag%"
      false:
        - "&cYou do not have permission to view this!"

# The End
# Enjoy <3