name: RoseChat
main: dev.rosewood.rosechat.RoseChat
version: 1.0.0
api-version: "1.16"
description: A customisable chat plugin.
author: Lilac
softdepend: [PlaceholderAPI, Vault, Essentials, LuckPerms]
commands:
  rosechat:
    aliases: [rc]
    description: Main command for RoseChat.
  message:
    aliases: [msg, whisper, tell, m, w, t, pm]
    description: Send a message to another player.
  reply:
    aliases: [reply, r]
    description: Replies to a message from another player.
  socialspy:
    aliases: [ss, spy]
    description: Allows a player to see private messages.
  togglemessage:
    aliases: [togglemessages, togglepm, togglemsg, togglemsgs]
    description: Toggles receiving messages.
  togglesound:
    aliases: [togglesounds, toggleping, toggletag]
    description: Toggles receiving sounds on messages or tags.
  toggleemotes:
    aliases: [toggleemote]
    description: Toggles formatting emotes when sent.
  channel:
    aliases: [c]
    description: Talk in a chat channel.
  chat:
    aliases: [cc, chatchannel]
    description: Admin commands for chat channels.
  color:
    aliases: [chatcolor]
    description: Set a default chat color.
  gc:
    aliases: [group, groupchat]
    description: Displays group chat commands.
permissions:
  rosechat.*:
    description: Gives access to all Rosechat permissions.
    children:
      - rosechat.chat
      - rosechat.bypass
      - rosechat.message
      - rosechat.reply
      - rosechat.spy
      - rosechat.togglemessage
      - rosechat.togglesound
      - rosechat.toggleemotes
      - rosechat.channel
      - rosechat.admin
      - rosechat.group
      - rosechat.chatcolor
  rosechat.chat:
    description: Allows a player to chat.
    default: not op
  rosechat.chat.color:
    description: Allows a player to use color in chat.
    default: op
  rosechat.chat.format:
    description: Allows a player to use formatting in chat.
    default: op
  rosechat.chat.magic:
    description: Allows a player to use the magic formatting in chat.
    default: op
  rosechat.chat.spam:
    description: Allows a player to bypass the spam filter.
    default: op
  rosechat.chat.language:
    description: Allows a player to bypass the language filter.
    default: op
  rosechat.chat.caps:
    description: Allows a player to bypass the caps filter.
    default: op
  rosechat.chat.links:
    description: Allows a player to bypass the URL filter.
    default: op
  rosechat.tag.*:
    description: Allows a player to use all tags.
    default: op
  rosechat.replacement.*:
    description: Allows a player to use all emotes.
    default: op
  rosechat.message:
    description: Allows a player to use /message.
    default: op
  rosechat.message.color:
    description: Allows a player to use color in /message.
    default: op
  rosechat.message.format:
    description: Allows a player to use formatting in /message.
    default: op
  rosechat.message.magic:
    description: Allows a player to use magic in /message.
    default: op
  rosechat.message.caps:
    description: Allows a player to use caps in /message.
    default: op
  rosechat.message.language:
    description: Allows a player to use bad language in /message.
    default: op
  rosechat.message.links:
    description: Allows a player to use links in /message.
    default: op
  rosechat.message.spam:
    description: Allows a player to spam in /message.
    default: op
  rosechat.reply:
    description: Allows a player to use /reply.
    default: op
  rosechat.spy:
    description: Allows a player to use /socialspy.
    default: op
  rosechat.togglemessage:
    description: Allows a player to use /togglemessage.
    default: op
  rosechat.togglesound:
    description: Allows a player to use /togglesound.
    default: op
  rosechat.toggleemotes:
    description: Allows a player to use /toggleemotes.
    default: op
  rosechat.channel:
    description: Allows a player to access channels.
    default: op
  rosechat.admin.mute:
    description: Allows a player to mute a chat channel.
    default: op
  rosechat.admin.clear:
    description: Allows a player to clear a chat channel.
    default: op
  rosechat.admin.move:
    description: Allows a player to move a player to a chat channel.
    default: op
  rosechat.admin.sudo:
    description: Allows a player to chat as another player.
    default: op
  rosechat.group.create:
    description: Allows a player to create a group.
    default: op
  rosechat.group.invite:
    description: Allows a player to invite a player to a group.
    default: op
  rosechat.group.kick:
    description: Allows a player to kick a player from a group.
    default: op
  rosechat.group.accept:
    description: Allows a player to accept a group invite.
    default: op
  rosechat.group.leave:
    description: Allows a player to leave a group.
    default: op
  rosechat.group.disband:
    description: Allows a player to disband a group.
    default: op
  rosechat.group.members:
    description: Allows a player to see group members.
    default: op
  rosechat.chatcolor:
    description: Allows a player to set a default chat color.
    default: op