name: RoseChat
main: dev.rosewood.rosechat.RoseChat
version: 1.0.0
api-version: "1.16"
description: A customisable chat plugin.
author: Lilac
softdepend: [PlaceholderAPI, Vault, Essentials, LuckPerms]
commands:
  rosechat:
    aliases: [rc]
    description: Main command for RoseChat.
  message:
    aliases: [msg, whisper, tell, m, w, t, pm]
    description: Send a message to another player.
  reply:
    aliases: [reply, r]
    description: Replies to a message from another player.
  socialspy:
    aliases: [ss, spy]
    description: Allows a player to see private messages.
  togglemessage:
    aliases: [togglemessages, togglepm, togglemsg, togglemsgs]
    description: Toggles receiving messages.
  togglesound:
    aliases: [togglesounds, toggleping, toggletag]
    description: Toggles receiving sounds on messages or tags.
  toggleemotes:
    aliases: [toggleemote]
    description: Toggles formatting emotes when sent.
  channel:
    aliases: [c]
    description: Talk in a chat channel.
permissions:
  rosechat.*:
    description: Gives access to all Rosechat permissions.
    children:
      - rosechat.chat
      - rosechat.bypass
      - rosechat.message
      - rosechat.reply
      - rosechat.spy
      - rosechat.togglemessage
      - rosechat.togglesound
      - rosechat.toggleemotes
      - rosechat.channel
  rosechat.chat:
    description: Allows a player to chat.
    default: not op
  rosechat.chat.color:
    description: Allows a player to use color in chat.
    default: op
  rosechat.chat.format:
    description: Allows a player to use formatting in chat.
    default: op
  rosechat.chat.magic:
    description: Allows a player to use the magic formatting in chat.
    default: op
  rosechat.chat.tag:
    description: Allows a player to tag other players.
    default: op
  rosechat.bypass:
    description: Allows a player to bypass filters.
    default: op
  rosechat.bypass.spam:
    description: Allows a player to bypass the spam filter.
    default: op
  rosechat.bypass.language:
    description: Allows a player to bypass the language filter.
    default: op
  rosechat.bypass.caps:
    description: Allows a player to bypass the caps filter.
    default: op
  rosechat.bypass.links:
    description: Allows a player to bypass the URL filter.
    default: op
  rosechat.message:
    description: Allows a player to use /message.
    default: op
  rosechat.message.color:
    description: Allows a player to use color in /message.
    default: op
  rosechat.message.format:
    description: Allows a player to use formatting in /message.
    default: op
  rosechat.message.magic:
    description: Allows a player to use magic in /message.
    default: op
  rosechat.message.caps:
    description: Allows a player to use caps in /message.
    default: op
  rosechat.message.language:
    description: Allows a player to use bad language in /message.
    default: op
  rosechat.message.links:
    description: Allows a player to use links in /message.
    default: op
  rosechat.message.spam:
    description: Allows a player to spam in /message.
    default: op
  rosechat.reply:
    description: Allows a player to use /reply.
    default: op
  rosechat.spy:
    description: Allows a player to use /socialspy.
    default: op
  rosechat.togglemessage:
    description: Allows a player to use /togglemessage.
    default: op
  rosechat.togglesound:
    description: Allows a player to use /togglesound.
    default: op
  rosechat.toggleemotes:
    description: Allows a player to use /toggleemotes.
    default: op
  rosechat.channel:
    description: Allows a player to access channels.
    default: op