name: RoseChat
version: '@version@'
authors: [Lilac, Esophose]
website: https://www.spigotmc.org/resources/rosechat/
main: dev.rosewood.rosechat.RoseChat
api-version: '1.13'
softdepend:
  - Vault
  - PlaceholderAPI
  - DiscordSRV
  - ProtocolLib
  - Essentials
  - LuckPerms
commands:
  rosechat:
    aliases: [rc]
    description: Main command for RoseChat.
  message:
    aliases: [msg, whisper, tell, pm, m, w, t]
    description: Send a message to another player.
  reply:
    aliases: [r]
    description: Replies to a message from another player.
  socialspy:
    aliases: [ss, spy]
    description: Allows a player to see private messages.
  togglemessage:
    aliases: [togglemessages, togglepm, togglemsg, togglemsgs, togglepms]
    description: Toggles receiving messages.
  togglesound:
    aliases: [togglesounds, toggleping, toggletag]
    description: Toggles receiving sounds on messages or tags.
  toggleemoji:
    aliases: [toggleemojis]
    description: Toggles automatically creating emojis.
  channel:
    aliases: [c]
    description: Accesses a chat channel.
  chat:
    aliases: [cc, chatchannel]
    description: Displays admin commands for chat channels.
  color:
    aliases: [chatcolor, colour, chatcolour]
    description: Set a default chat color.
  mute:
    description: Mute a player.
  gc:
    aliases: [group, groupchat]
    description: Displays group chat commands.
  gcm:
    aliases: [gcm, gcmsg, gmsg]
    description: Send a message in a group chat.
  nickname:
    aliases: [nick]
    description: Set a nickname.
  ignore:
    description: Ignore a player.
  delmsg:
    description: Delete a message.
permissions:
  rosechat.*:
    description: Inherits all plugin permissions.
    children:
      rosechat.reload: true
      rosechat.color: true
      rosechat.hex: true
      rosechat.rainbow: true
      rosechat.gradient: true
      rosechat.format: true
      rosechat.magic: true
      rosechat.spam: true
      rosechat.language: true
      rosechat.caps: true
      rosechat.links: true
      rosechat.placeholders: true
      rosechat.tags: true
      rosechat.replacements: true
      rosechat.emojis: true
      rosechat.chat: true
      rosechat.message: true
      rosechat.reply: true
      rosechat.tag: true
      rosechat.replacement: true
      rosechat.emoji: true
      rosechat.spy: true
      rosechat.togglemessage: true
      rosechat.togglesound: true
      rosechat.toggleemoji: true
      rosechat.mute: true
      rosechat.channel: true
      rosechat.admin: true
      rosechat.chatcolor: true
      rosechat.group: true
      rosechat.groups: true
      rosechat.nickname: true
      rosechat.ignore: true
      rosechat.deletemessages: true
  rosechat.reload:
    description: Allows using the reload command.
    default: op
  rosechat.chat:
    description: Allows using chat.
    default: not op
  rosechat.color:
    description: Allows using color codes.
    default: op
    children:
      rosechat.color.chat: true
      rosechat.color.message: true
      rosechat.color.channel: true
      rosechat.color.group: true
      rosechat.color.nickname: true
  rosechat.format:
    description: Allows using formatting codes.
    default: op
    children:
      rosechat.format.chat: true
      rosechat.format.message: true
      rosechat.format.channel: true
      rosechat.format.group: true
      rosechat.format.nickname: true
  rosechat.magic:
    description: Allows using the magic fomatting code.
    default: op
    children:
      rosechat.magic.chat: true
      rosechat.magic.message: true
      rosechat.magic.channel: true
      rosechat.magic.group: true
      rosechat.magic.nickname: true
  rosechat.hex:
    description: Allows using hex color codes.
    default: op
    children:
      rosechat.hex.chat: true
      rosechat.hex.message: true
      rosechat.hex.channel: true
      rosechat.hex.group: true
      rosechat.hex.nickname: true
  rosechat.gradient:
    description: Allows using the gradient code.
    default: op
    children:
      rosechat.gradient.chat: true
      rosechat.gradient.message: true
      rosechat.gradient.channel: true
      rosechat.gradient.group: true
      rosechat.gradient.nickname: true
  rosechat.rainbow:
    description: Allows using the rainbow code.
    default: op
    children:
      rosechat.rainbow.chat: true
      rosechat.rainbow.message: true
      rosechat.rainbow.channel: true
      rosechat.rainbow.group: true
      rosechat.rainbow.nickname: true
  rosechat.spam:
    description: Allows bypassing the spam filter.
    default: op
    children:
      rosechat.spam.chat: true
      rosechat.spam.message: true
      rosechat.spam.channel: true
      rosechat.spam.group: true
      rosechat.spam.nickname: true
  rosechat.language:
    description: Allows bypassing the language filter.
    default: op
    children:
      rosechat.language.chat: true
      rosechat.language.message: true
      rosechat.language.channel: true
      rosechat.language.group: true
      rosechat.language.nickname: true
  rosechat.caps:
    description: Allows bypassing the caps filter.
    default: op
    children:
      rosechat.caps.chat: true
      rosechat.caps.message: true
      rosechat.caps.channel: true
      rosechat.caps.group: true
      rosechat.caps.nickname: true
  rosechat.links:
    description: Allows bypassing the URL filter.
    default: op
    children:
      rosechat.links.chat: true
      rosechat.links.message: true
      rosechat.links.channel: true
      rosechat.links.group: true
      rosechat.links.nickname: true
  rosechat.placeholders:
    description: Allows using placeholders.
    default: op
    children:
      rosechat.placeholders.chat: true
      rosechat.placeholders.message: true
      rosechat.placeholders.channel: true
      rosechat.placeholders.group: true
      rosechat.placeholders.nickname: true
  rosechat.tags:
    description: Allows using tags.
    default: op
    children:
      rosechat.tags.chat: true
      rosechat.tags.message: true
      rosechat.tags.channel: true
      rosechat.tags.group: true
      rosechat.tags.nickname: true
  rosechat.replacements:
    description: Allows using replacements.
    default: op
    children:
      rosechat.replacements.chat: true
      rosechat.replacements.message: true
      rosechat.replacements.channel: true
      rosechat.replacements.group: true
      rosechat.replacements.nickname: true
  rosechat.emojis:
    description: Allows using emojis.
    default: op
    children:
      rosechat.emojis.chat: true
      rosechat.emojis.message: true
      rosechat.emojis.channel: true
      rosechat.emojis.group: true
      rosechat.emojis.nickname: true
  rosechat.message:
    description: Allows using the message command.
    default: op
  rosechat.reply:
    description: Allows using the reply command.
    default: op
  rosechat.tag:
    description: Allows using a specific tag.
    default: op
  rosechat.replacement:
    description: Allows using a specific replacement.
    default: op
  rosechat.emote:
    description: Allows using a specific emote.
    default: op
  rosechat.spy:
    description: Allows using social spy.
    default: op
  rosechat.spy.message:
    description: Allows using message social spy.
    default: op
  rosechat.spy.channel:
    description: Allows using channel social spy.
    default: op
  rosechat.spy.group:
    description: Allows using group social spy.
    default: op
  rosechat.togglemessage:
    description: Allows using the togglemessage command.
    default: op
  rosechat.togglesound:
    description: Allows using the togglesound command.
    default: op
  rosechat.toggleemoji:
    description: Allows using the toggleemoji command.
    default: op
  rosechat.mute:
    description: Allows using the mute command.
    default: op
  rosechat.mute.bypass:
    description: Allows chatting while being muted.
    default: op
  rosechat.channel:
    description: Allows using the channel command.
    default: op
  rosechat.admin.mute:
    description: Allows using the chat mute command.
    default: op
  rosechat.admin.clear:
    description: Allows using the chat clear command.
    default: op
  rosechat.admin.move:
    description: Allows using the chat move command.
    default: op
  rosechat.admin.sudo:
    description: Allows using the chat sudo command.
    default: op
  rosechat.chatcolor:
    description: Allows using the chatcolor command.
    default: op
  rosechat.group.create:
    description: Allows using the group create command.
    default: op
  rosechat.group.disband:
    description: Allows using the group disband command.
    default: op
  rosechat.group.invite:
    description: Allows using the group invite command.
    default: op
  rosechat.group.kick:
    description: Allows using the group kick command.
    default: op
  rosechat.group.accept:
    description: Allows using the group accept command.
    default: op
  rosechat.group.deny:
    description: Allows using the group deny command.
    default: op
  rosechat.group.leave:
    description: Allows using the group leave command.
    default: op
  rosechat.group.members:
    description: Allows using the group members command.
    default: op
  rosechat.group.rename:
    description: Allows using the group rename command.
    default: op
  rosechat.group.message:
    description: Allows using the group message command.
    default: op
  rosechat.group.admin:
    description: Allows managing other groups.
    default: op
  rosechat.groups:
    description: Limits the amount of groups a player can be in.
    default: op
  rosechat.nickname:
    description: Allows using the nickname command.
    default: op
  rosechat.nickname.others:
    description: Allows setting the nickname of another player.
    default: op
  rosechat.deletemessages:
    description: Allows players to delete messages
    default: op
    children:
      rosechat.deletemessages.client: true
      rosechat.deletemessages.self: true
      rosechat.deletemessages.others: true
      rosechat.deletemessages.see: true
