name: RoseChat
version: '@version@'
authors: [Lilac, Esophose]
website: https://www.spigotmc.org/resources/rosechat/
main: dev.rosewood.rosechat.RoseChat
api-version: '1.13'
softdepend:
  - Essentials
  - LuckPerms
  - PlaceholderAPI
  - Vault
  - DiscordSRV
commands:
  rosechat:
    aliases: [rc]
    description: Main command for RoseChat.
  message:
    aliases: [msg, whisper, tell, pm, m, w, t]
    description: Send a message to another player.
  reply:
    aliases: [r]
    description: Replies to a message from another player.
  socialspy:
    aliases: [ss, spy]
    description: Allows a player to see private messages.
  togglemessage:
    aliases: [togglemessages, togglepm, togglemsg, togglemsgs, togglepms]
    description: Toggles receiving messages.
  togglesound:
    aliases: [togglesounds, toggleping, toggletag]
    description: Toggles receiving sounds on messages or tags.
  toggleemoji:
    aliases: [toggleemojis]
    description: Toggles automatically creating emojis.
  channel:
    aliases: [c]
    description: Accesses a chat channel.
  chat:
    aliases: [cc, chatchannel]
    description: Displays admin commands for chat channels.
  color:
    aliases: [chatcolor, colour, chatcolour]
    description: Set a default chat color.
  mute:
    description: Mute a player.
  gc:
    aliases: [group, groupchat]
    description: Displays group chat commands.
  gcm:
    aliases: [gcm, gcmsg, gmsg]
    description: Send a message in a group chat.
  nickname:
    aliases: [nick]
    description: Set a nickname.
permissions:
  rosechat.*:
    description: Inherits all plugin permissions.
    children:
      rosechat.color: true
      rosechat.hex: true
      rosechat.rainbow: true
      rosechat.gradient: true
      rosechat.format: true
      rosechat.magic: true
      rosechat.spam: true
      rosechat.language: true
      rosechat.caps: true
      rosechat.links: true
      rosechat.placeholders: true
      rosechat.tags: true
      rosechat.replacements: true
      rosechat.emojis: true
      rosechat.chat: true
      rosechat.message: true
      rosechat.reply: true
      rosechat.tag: true
      rosechat.replacement: true
      rosechat.emoji: true
      rosechat.spy: true
      rosechat.togglemessage: true
      rosechat.togglesound: true
      rosechat.toggleemoji: true
      rosechat.mute: true
      rosechat.channel: true
      rosechat.admin: true
      rosechat.chatcolor: true
      rosechat.group: true
      rosechat.groups: true
      rosechat.nickname: true
  rosechat.chat:
    description: Allows using chat.
    default: not op
  rosechat.color:
    description: Allows using color codes.
    default: op
    children:
      - rosechat.color.chat
      - rosechat.color.message
      - rosechat.color.channel
      - rosechat.color.group
      - rosechat.color.nickname
  rosechat.format:
    description: Allows using formatting codes.
    default: op
    children:
      - rosechat.format.chat
      - rosechat.format.message
      - rosechat.format.channel
      - rosechat.format.group
      - rosechat.format.nickname
  rosechat.magic:
    description: Allows using the magic fomatting code.
    default: op
    children:
      - rosechat.magic.chat
      - rosechat.magic.message
      - rosechat.magic.channel
      - rosechat.magic.group
      - rosechat.magic.nickname
  rosechat.hex:
    description: Allows using hex color codes.
    default: op
    children:
      - rosechat.hex.chat
      - rosechat.hex.message
      - rosechat.hex.channel
      - rosechat.hex.group
      - rosechat.hex.nickname
  rosechat.gradient:
    description: Allows using the gradient code.
    default: op
    children:
      - rosechat.gradient.chat
      - rosechat.gradient.message
      - rosechat.gradient.channel
      - rosechat.gradient.group
      - rosechat.gradient.nickname
  rosechat.rainbow:
    description: Allows using the rainbow code.
    default: op
    children:
      - rosechat.rainbow.chat
      - rosechat.rainbow.message
      - rosechat.rainbow.channel
      - rosechat.rainbow.group
      - rosechat.rainbow.nickname
  rosechat.spam:
    description: Allows bypassing the spam filter.
    default: op
    children:
      - rosechat.spam.chat
      - rosechat.spam.message
      - rosechat.spam.channel
      - rosechat.spam.group
      - rosechat.spam.nickname
  rosechat.language:
    description: Allows bypassing the language filter.
    default: op
    children:
      - rosechat.language.chat
      - rosechat.language.message
      - rosechat.language.channel
      - rosechat.language.group
      - rosechat.language.nickname
  rosechat.caps:
    description: Allows bypassing the caps filter.
    default: op
    children:
      - rosechat.caps.chat
      - rosechat.caps.message
      - rosechat.caps.channel
      - rosechat.caps.group
      - rosechat.caps.nickname
  rosechat.links:
    description: Allows bypassing the URL filter.
    default: op
    children:
      - rosechat.links.chat
      - rosechat.links.message
      - rosechat.links.channel
      - rosechat.links.group
      - rosechat.links.nickname
  rosechat.placeholders:
    description: Allows using placeholders.
    default: op
    children:
      - rosechat.placeholders.chat
      - rosechat.placeholders.message
      - rosechat.placeholders.channel
      - rosechat.placeholders.group
      - rosechat.placeholders.nickname
  rosechat.tags:
    description: Allows using tags.
    default: op
    children:
      - rosechat.tags.chat
      - rosechat.tags.message
      - rosechat.tags.channel
      - rosechat.tags.group
      - rosechat.tags.nickname
  rosechat.replacements:
    description: Allows using replacements.
    default: op
    children:
      - rosechat.replacements.chat
      - rosechat.replacements.message
      - rosechat.replacements.channel
      - rosechat.replacements.group
      - rosechat.replacements.nickname
  rosechat.emojis:
    description: Allows using emojis.
    default: op
    children:
      - rosechat.emojis.chat
      - rosechat.emojis.message
      - rosechat.emojis.channel
      - rosechat.emojis.group
      - rosechat.emojis.nickname
  rosechat.message:
    description: Allows using the message command.
    default: op
  rosechat.reply:
    description: Allows using the reply command.
    default: op
  rosechat.tag:
    description: Allows using a specific tag.
    default: op
  rosechat.replacement:
    description: Allows using a specific replacement.
    default: op
  rosechat.emote:
    description: Allows using a specific emote.
    default: op
  rosechat.spy:
    description: Allows using social spy.
    default: op
  rosechat.spy.message:
    description: Allows using message social spy.
    default: op
  rosechat.spy.channel:
    description: Allows using channel social spy.
    default: op
  rosechat.spy.group:
    description: Allows using group social spy.
    default: op
  rosechat.togglemessage:
    description: Allows using the togglemessage command.
    default: op
  rosechat.togglesound:
    description: Allows using the togglesound command.
    default: op
  rosechat.toggleemoji:
    description: Allows using the toggleemoji command.
    default: op
  rosechat.mute:
    description: Allows using the mute command.
    default: op
  rosechat.mute.bypass:
    description: Allows chatting while being muted.
    default: op
  rosechat.channel:
    description: Allows using the channel command.
    default: op
  rosechat.admin.mute:
    description: Allows using the chat mute command.
    default: op
  rosechat.admin.clear:
    description: Allows using the chat clear command.
    default: op
  rosechat.admin.move:
    description: Allows using the chat move command.
    default: op
  rosechat.admin.sudo:
    description: Allows using the chat sudo command.
    default: op
  rosechat.chatcolor:
    description: Allows using the chatcolor command.
    default: op
  rosechat.group.create:
    description: Allows using the group create command.
    default: op
  rosechat.group.disband:
    description: Allows using the group disband command.
    default: op
  rosechat.group.invite:
    description: Allows using the group invite command.
    default: op
  rosechat.group.kick:
    description: Allows using the group kick command.
    default: op
  rosechat.group.accept:
    description: Allows using the group accept command.
    default: op
  rosechat.group.deny:
    description: Allows using the group deny command.
    default: op
  rosechat.group.leave:
    description: Allows using the group leave command.
    default: op
  rosechat.group.members:
    description: Allows using the group members command.
    default: op
  rosechat.group.rename:
    description: Allows using the group rename command.
    default: op
  rosechat.group.message:
    description: Allows using the group message command.
    default: op
  rosechat.group.admin:
    description: Allows managing other groups.
    default: op
  rosechat.groups:
    description: Limits the amount of groups a player can be in.
    default: op
  rosechat.nickname:
    description: Allows using the nickname command.
    default: op
  rosechat.nickname.others:
    description: Allows setting the nickname of another player.
    default: op
